name: Publish to GitHub Pages 
on:
  [push]
permissions:
  contents: write
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v1

      - name: Publish generated content to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.7.3
        with:
          folder: public
          branch: new

