name: Publish to GitHub Pages 
on:
  [push]
permissions:
  contents: write
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install
        run: sudo apt install emacs-nox --yes
      - name: Build
        run: ./build.sh
      - name: Publish
        uses: JamesIves/github-pages-deploy-action@v4.7.3
        with:
          folder: public
          branch: new

